---
name: Makefile CI

on:
  push: null

permissions:
  contents: read # This is sufficient for read access.
  statuses: write # This is needed to update status checks.

jobs:
  compile:
    name: Compile C++ Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Project and Run Tests
      run: make distcheck

    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binary
        path: ./bin/test_suite
        retention-days: 3

  test-valgrind:
    name: Test Memory Leaks with Valgrind
    needs: compile
    uses: Vianpyro/Valgrind/.github/workflows/valgrind.yml@v2
    with:
      name: test_suite
