---
name: Makefile CI

on:
  push: null

permissions:
  contents: read # This is sufficient for read access.
  statuses: write # This is needed to update status checks.
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
