---
name: Makefile CI

on:
  push: null

permissions:
  contents: read # This is sufficient for read access.
  statuses: write # This is needed to update status checks.

jobs:
  compile:
    name: Compile C++ Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: bin/ShatteredKingdom

  test-valgrind:
    name: Test Memory Leaks with Valgrind
    needs: compile
    uses: Vianpyro/Valgrind@v1
